### PR TITLE
OpenShift domains support

### PR DESCRIPTION
**Pull request by cianclarke**
@david-martin Fixes the issues we saw tonight with domains - allows domain list & create. 
1.0.0 version bump, because it fundamentally alters how domains are handled from before

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@cianclarke this looks good. Was caught out by lack of response logging a minute ago.

**Comment by jasonmadigan** [comment]
@cianclarke has this been published? Can see a 1.0.1 in npm

**Comment by cianclarke** [comment]
Has indeed, yep

**Comment by cianclarke** [comment]
Don't think fh-supercore is using it on the branch you're working off yet however

**Comment by jasonmadigan** [comment]
@cianclarke have updated supercore branch to use ~1.0.0 instead of 1.0.0

**Pull request merged**
